//Mock nao mais utilizado

// export const listaPerguntas = [
//     {id:1,
//         idSala: 1,
//         mensagem: 'Qual é a diferença entre let, const e var no JavaScript?',
//         usuario: 'Pedro Alvares Cabral'},
//     {id:2,
//         idSala: 1,
//         mensagem: 'O que é uma função de callback no JavaScript? Como você pode usá-la?',
//         usuario: 'Alexandre Dante'},
//     {id:3,
//         idSala: 1,
//         mensagem: 'Explique o que é hoisting em JavaScript e como isso afeta o código.',
//         usuario: 'Murilo Carioca Silva'},
//     {id:4,
//         idSala: 2,
//         mensagem: 'O que é JSX no React e por que é usado?',
//         usuario: 'Alexandre Dante'},
//     {id:5,
//         idSala: 2,
//         mensagem: 'Qual é a diferença entre componentes funcionais e componentes de classe no React?',
//         usuario: 'Murilo Carioca Silva'},
//     {id:6,
//         idSala: 3,
//         mensagem: 'O que é o PostgreSQL e quais são algumas de suas principais características?',
//         usuario: 'Alexandre Dante'},
//     {id:7,
//         idSala: 3,
//         mensagem: 'Explique a diferença entre chaves primárias e chaves estrangeiras no PostgreSQL.',
//         usuario: 'Murilo Carioca Silva'},
//     {id:8,
//         idSala: 3,
//         mensagem: 'Como você pode realizar uma junção (join) entre duas tabelas no PostgreSQL?',
//         usuario: 'Alexandre Dante'},
//     {id:9,
//         idSala: 3,
//         mensagem: 'Como você pode implementar uma função personalizada no PostgreSQL usando a linguagem de programação PL/pgSQL para calcular a soma de todos os números primos em uma tabela?',
//         usuario: 'Murilo Carioca Silva'},
    
// ]

